# Generated by Django 3.1.12 on 2024-12-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKomAPP', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
